import 'dart:convert';
import 'image.dart';
import 'package:flutter/material.dart';
import 'data.dart';
import 'package:http/http.dart' as http;


void main()
{
  runApp(MaterialApp(home: myapp1(),));
}

class myapp extends StatefulWidget {
  const myapp({Key? key}) : super(key: key);

  @override
  State<myapp> createState() => _myappState();
}

class _myappState extends State<myapp> {
  List list=[];
  List<Autogenerated> userlist=[];
  
  Future<List> get() async{
    var url =Uri.parse('https://jsonplaceholder.typicode.com/posts');
    var response = await http.get(url);

    list=jsonDecode(response.body);
    list.forEach((element) {
      userlist.add(Autogenerated.fromMap(element));
    });
    print(list);
    return userlist;
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("data"),),
      body: FutureBuilder(builder: (context, snapshot) {
        if(snapshot.connectionState==ConnectionState.done)
        {
          List<Autogenerated> val=snapshot.data as List<Autogenerated>;
          return ListView.builder(itemBuilder: (context, index) {
            return Card(child:
            ListTile(
              title: Text("${val[index].title}",),
              subtitle: Text("${val[index].body}"),
              leading: Text("${val[index].id}"),
            ),
            );
          },
            itemCount: list.length,);
        }
        else
          {
            return Center(child: CircularProgressIndicator(),);
          }
      },
        future: get(),
      ),
    );
  }
}

class myapp1 extends StatefulWidget {
  const myapp1({Key? key}) : super(key: key);

  @override
  State<myapp1> createState() => _myapp1State();
}

class _myapp1State extends State<myapp1> {

  List list=[];
  List<rest> userlist=[];

  Future<List<rest>> get() async{
    var url =Uri.parse("https://s3-us-west-2.amazonaws.com/appsdeveloperblog.com/tutorials/files/cats.json");
    var response = await http.get(url);

    list=jsonDecode(response.body);
    list.forEach((element) {
      userlist.add(rest.fromJson(element));
    });
    print(list);
    return userlist;
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("data"),),
      body: FutureBuilder(builder: (context, snapshot) {
        if(snapshot.connectionState==ConnectionState.done)
        {
          List<rest> val=snapshot.data as List<rest>;
          return ListView.builder(itemBuilder: (context, index) {
            return Card(child:
            ListTile(
              leading: Image.network("${val[index].url!}"),
            ),
            );
          },
            itemCount: list.length,);
        }
        else
        {
          return Center(child: CircularProgressIndicator(),);
        }
      },
        future: get(),
      ),
    );
  }
}

